modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "https://github.com/LocalizedMC/TextureLocaleRedirector"
authors = "Wulian233, TexTrue"
description = '''
Support redirecting resource paths based on the game language to achieve multi-language texture loading. By extending the vanilla resource loading mechanism, it provides native multi-language texture support for resource packs, enabling localization of texture assets.
'''
logoFile = "assets/${id}/icon.png"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
